print("..............................")
print(".         ppppppppp")
print(".     pp            pp        .")
print(".    pp              pp       .")
print(".   pp    PP    PP    pp      .")
print(".  pp     PP    PP     pp     .")
print(". pp                    pp    .")
print(". pp                    pp    .")
print(". pp   PP          PP   pp    .")
print(".  pp   PP        PP   pp     .")
print(".   pp   PPPPPPPPPP   pp      .")
print(".    pp              PP       .")
print(".         ppppppppp           .")
print("...............................")